name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened and what did you expect?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Integration version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Home Assistant version, installation type, Modbus gateway, etc.
      placeholder: "HA 2024.xx, Container, Waveshare RS485-TCP, Unit-ID 3"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste logs with debug enabled for this integration and pymodbus.
      render: shell
